revoke delete on table "public"."testTable" from "anon";

revoke insert on table "public"."testTable" from "anon";

revoke references on table "public"."testTable" from "anon";

revoke select on table "public"."testTable" from "anon";

revoke trigger on table "public"."testTable" from "anon";

revoke truncate on table "public"."testTable" from "anon";

revoke update on table "public"."testTable" from "anon";

revoke delete on table "public"."testTable" from "authenticated";

revoke insert on table "public"."testTable" from "authenticated";

revoke references on table "public"."testTable" from "authenticated";

revoke select on table "public"."testTable" from "authenticated";

revoke trigger on table "public"."testTable" from "authenticated";

revoke truncate on table "public"."testTable" from "authenticated";

revoke update on table "public"."testTable" from "authenticated";

revoke delete on table "public"."testTable" from "service_role";

revoke insert on table "public"."testTable" from "service_role";

revoke references on table "public"."testTable" from "service_role";

revoke select on table "public"."testTable" from "service_role";

revoke trigger on table "public"."testTable" from "service_role";

revoke truncate on table "public"."testTable" from "service_role";

revoke update on table "public"."testTable" from "service_role";

alter table "public"."testTable" drop constraint "testTable_pkey";

drop index if exists "public"."testTable_pkey";

drop table "public"."testTable";

create table "public"."teenieping" (
    "id" bigint generated by default as identity not null,
    "name_ko" character varying not null,
    "name_en" character varying not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."teenieping" enable row level security;

CREATE UNIQUE INDEX teenieping_name_en_key ON public.teenieping USING btree (name_en);

CREATE UNIQUE INDEX teenieping_name_ko_key ON public.teenieping USING btree (name_ko);

CREATE UNIQUE INDEX teenieping_pkey ON public.teenieping USING btree (id);

alter table "public"."teenieping" add constraint "teenieping_pkey" PRIMARY KEY using index "teenieping_pkey";

alter table "public"."teenieping" add constraint "teenieping_name_en_key" UNIQUE using index "teenieping_name_en_key";

alter table "public"."teenieping" add constraint "teenieping_name_ko_key" UNIQUE using index "teenieping_name_ko_key";

grant delete on table "public"."teenieping" to "anon";

grant insert on table "public"."teenieping" to "anon";

grant references on table "public"."teenieping" to "anon";

grant select on table "public"."teenieping" to "anon";

grant trigger on table "public"."teenieping" to "anon";

grant truncate on table "public"."teenieping" to "anon";

grant update on table "public"."teenieping" to "anon";

grant delete on table "public"."teenieping" to "authenticated";

grant insert on table "public"."teenieping" to "authenticated";

grant references on table "public"."teenieping" to "authenticated";

grant select on table "public"."teenieping" to "authenticated";

grant trigger on table "public"."teenieping" to "authenticated";

grant truncate on table "public"."teenieping" to "authenticated";

grant update on table "public"."teenieping" to "authenticated";

grant delete on table "public"."teenieping" to "service_role";

grant insert on table "public"."teenieping" to "service_role";

grant references on table "public"."teenieping" to "service_role";

grant select on table "public"."teenieping" to "service_role";

grant trigger on table "public"."teenieping" to "service_role";

grant truncate on table "public"."teenieping" to "service_role";

grant update on table "public"."teenieping" to "service_role";


