drop policy "Enable read access for all users" on "public"."teenieping";

drop policy "Enable read access for all users" on "public"."teenieping_image";

create table "public"."quiz_log" (
    "id" bigint generated by default as identity not null,
    "quiz_token" character varying not null,
    "question" character varying not null,
    "selected_option" character varying not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."quiz_log" enable row level security;

create table "public"."quiz_publish_log" (
    "id" bigint generated by default as identity not null,
    "quiz_token" character varying not null,
    "response" json not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."quiz_publish_log" enable row level security;

alter table "public"."ranking" add column "quiz_token" character varying not null;

CREATE UNIQUE INDEX quiz_log_pkey ON public.quiz_log USING btree (id);

CREATE INDEX quiz_log_quiz_token_idx ON public.quiz_log USING btree (quiz_token);

CREATE UNIQUE INDEX quiz_publish_log_pkey ON public.quiz_publish_log USING btree (id);

CREATE INDEX quiz_publish_log_quiz_token_idx ON public.quiz_publish_log USING btree (quiz_token);

alter table "public"."quiz_log" add constraint "quiz_log_pkey" PRIMARY KEY using index "quiz_log_pkey";

alter table "public"."quiz_publish_log" add constraint "quiz_publish_log_pkey" PRIMARY KEY using index "quiz_publish_log_pkey";

grant delete on table "public"."quiz_log" to "anon";

grant insert on table "public"."quiz_log" to "anon";

grant references on table "public"."quiz_log" to "anon";

grant select on table "public"."quiz_log" to "anon";

grant trigger on table "public"."quiz_log" to "anon";

grant truncate on table "public"."quiz_log" to "anon";

grant update on table "public"."quiz_log" to "anon";

grant delete on table "public"."quiz_log" to "authenticated";

grant insert on table "public"."quiz_log" to "authenticated";

grant references on table "public"."quiz_log" to "authenticated";

grant select on table "public"."quiz_log" to "authenticated";

grant trigger on table "public"."quiz_log" to "authenticated";

grant truncate on table "public"."quiz_log" to "authenticated";

grant update on table "public"."quiz_log" to "authenticated";

grant delete on table "public"."quiz_log" to "service_role";

grant insert on table "public"."quiz_log" to "service_role";

grant references on table "public"."quiz_log" to "service_role";

grant select on table "public"."quiz_log" to "service_role";

grant trigger on table "public"."quiz_log" to "service_role";

grant truncate on table "public"."quiz_log" to "service_role";

grant update on table "public"."quiz_log" to "service_role";

grant delete on table "public"."quiz_publish_log" to "anon";

grant insert on table "public"."quiz_publish_log" to "anon";

grant references on table "public"."quiz_publish_log" to "anon";

grant select on table "public"."quiz_publish_log" to "anon";

grant trigger on table "public"."quiz_publish_log" to "anon";

grant truncate on table "public"."quiz_publish_log" to "anon";

grant update on table "public"."quiz_publish_log" to "anon";

grant delete on table "public"."quiz_publish_log" to "authenticated";

grant insert on table "public"."quiz_publish_log" to "authenticated";

grant references on table "public"."quiz_publish_log" to "authenticated";

grant select on table "public"."quiz_publish_log" to "authenticated";

grant trigger on table "public"."quiz_publish_log" to "authenticated";

grant truncate on table "public"."quiz_publish_log" to "authenticated";

grant update on table "public"."quiz_publish_log" to "authenticated";

grant delete on table "public"."quiz_publish_log" to "service_role";

grant insert on table "public"."quiz_publish_log" to "service_role";

grant references on table "public"."quiz_publish_log" to "service_role";

grant select on table "public"."quiz_publish_log" to "service_role";

grant trigger on table "public"."quiz_publish_log" to "service_role";

grant truncate on table "public"."quiz_publish_log" to "service_role";

grant update on table "public"."quiz_publish_log" to "service_role";

create policy "Enable insert for all users"
on "public"."quiz_log"
as permissive
for insert
to public
with check (true);


create policy "Enable read access for all users"
on "public"."quiz_log"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."quiz_publish_log"
as permissive
for select
to public
using (true);


create policy "Enable read access for service role"
on "public"."teenieping"
as permissive
for select
to service_role
using (true);


create policy "Enable read access for service role"
on "public"."teenieping_image"
as permissive
for select
to service_role
using (true);



