create table "public"."teenieping_image" (
    "id" bigint generated by default as identity not null,
    "teenieping_id" bigint not null,
    "image_url" character varying not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."teenieping_image" enable row level security;

CREATE UNIQUE INDEX teenieping_image_pkey ON public.teenieping_image USING btree (id);

alter table "public"."teenieping_image" add constraint "teenieping_image_pkey" PRIMARY KEY using index "teenieping_image_pkey";

alter table "public"."teenieping_image" add constraint "teenieping_image_teenieping_id_fkey" FOREIGN KEY (teenieping_id) REFERENCES teenieping(id) ON DELETE CASCADE not valid;

alter table "public"."teenieping_image" validate constraint "teenieping_image_teenieping_id_fkey";

grant delete on table "public"."teenieping_image" to "anon";

grant insert on table "public"."teenieping_image" to "anon";

grant references on table "public"."teenieping_image" to "anon";

grant select on table "public"."teenieping_image" to "anon";

grant trigger on table "public"."teenieping_image" to "anon";

grant truncate on table "public"."teenieping_image" to "anon";

grant update on table "public"."teenieping_image" to "anon";

grant delete on table "public"."teenieping_image" to "authenticated";

grant insert on table "public"."teenieping_image" to "authenticated";

grant references on table "public"."teenieping_image" to "authenticated";

grant select on table "public"."teenieping_image" to "authenticated";

grant trigger on table "public"."teenieping_image" to "authenticated";

grant truncate on table "public"."teenieping_image" to "authenticated";

grant update on table "public"."teenieping_image" to "authenticated";

grant delete on table "public"."teenieping_image" to "service_role";

grant insert on table "public"."teenieping_image" to "service_role";

grant references on table "public"."teenieping_image" to "service_role";

grant select on table "public"."teenieping_image" to "service_role";

grant trigger on table "public"."teenieping_image" to "service_role";

grant truncate on table "public"."teenieping_image" to "service_role";

grant update on table "public"."teenieping_image" to "service_role";


